import { MarketplaceListing } from "@/types";

/**
 * Seed data standing in for the backend listings index. In production this is
 * replaced by the response from the search service; the shape stays the same.
 * Images use Unsplash source URLs so the grid renders real thumbnails.
 */
export const MOCK_LISTINGS: MarketplaceListing[] = [
  {
    id: "l1",
    title: "Operations Management by Krajewski",
    price: 450,
    category: "books",
    condition: "like_new",
    pickup: "hostel",
    imageUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&q=80",
    sellerName: "Rohan Verma",
    sellerBatch: "MBA '24",
    location: "Hostel 3",
    postedAgo: "2 hours ago",
    createdAtOffsetMinutes: 120,
  },
  {
    id: "l2",
    title: "HP Laptop 15s (8GB/512GB SSD)",
    price: 25000,
    category: "electronics",
    condition: "good",
    pickup: "hostel",
    imageUrl: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&q=80",
    sellerName: "Ananya Iyer",
    sellerBatch: "MBA '25",
    location: "Hostel 8",
    postedAgo: "4 hours ago",
    createdAtOffsetMinutes: 240,
  },
  {
    id: "l3",
    title: "Hero Sprint Pro Bicycle",
    price: 3800,
    category: "cycles",
    condition: "good",
    pickup: "hostel",
    imageUrl: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=600&q=80",
    sellerName: "Amit Sharma",
    sellerBatch: "MBA '24",
    location: "Hostel 12",
    postedAgo: "5 hours ago",
    createdAtOffsetMinutes: 300,
  },
  {
    id: "l4",
    title: "Study Desk Lamp with USB Port",
    price: 350,
    category: "appliances",
    condition: "fair",
    pickup: "academic_block",
    imageUrl: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&q=80",
    sellerName: "Priya Gupta",
    sellerBatch: "FPM '26",
    location: "Academic Block",
    postedAgo: "1 day ago",
    createdAtOffsetMinutes: 1440,
  },
  {
    id: "l5",
    title: "Ergonomic Office Chair",
    price: 1200,
    category: "furniture",
    condition: "like_new",
    pickup: "library",
    imageUrl: "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=600&q=80",
    sellerName: "Sneha Reddy",
    sellerBatch: "MBA '25",
    location: "Library",
    postedAgo: "12 hours ago",
    createdAtOffsetMinutes: 720,
  },
  {
    id: "l6",
    title: "Casio Scientific Calculator",
    price: 800,
    category: "electronics",
    condition: "good",
    pickup: "hostel",
    imageUrl: "https://images.unsplash.com/photo-1587145820266-a5951ee6f620?w=600&q=80",
    sellerName: "Vinay Kumar",
    sellerBatch: "MBA '24",
    location: "Hostel 1",
    postedAgo: "3 hours ago",
    createdAtOffsetMinutes: 180,
  },
  {
    id: "l7",
    title: "Lenovo ThinkPad E14 Gen 2",
    price: 32000,
    category: "electronics",
    condition: "like_new",
    pickup: "hostel",
    imageUrl: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=600&q=80",
    sellerName: "Rahul Verma",
    sellerBatch: "PGP 2025-27",
    location: "Hostel Block B",
    postedAgo: "2 days ago",
    createdAtOffsetMinutes: 2880,
  },
  {
    id: "l8",
    title: "Decathlon Rockrider ST100 (Blue)",
    price: 4500,
    category: "cycles",
    condition: "like_new",
    pickup: "hostel",
    imageUrl: "https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=600&q=80",
    sellerName: "Aditya Sharma",
    sellerBatch: "Batch of 2026",
    location: "Hostel 15",
    postedAgo: "Just now",
    createdAtOffsetMinutes: 5,
  },
  {
    id: "l9",
    title: "Wooden Study Table (Foldable)",
    price: 1800,
    category: "furniture",
    condition: "good",
    pickup: "hostel",
    imageUrl: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=600&q=80",
    sellerName: "Karan Mehta",
    sellerBatch: "MBA '25",
    location: "Hostel 6",
    postedAgo: "6 hours ago",
    createdAtOffsetMinutes: 360,
  },
  {
    id: "l10",
    title: "Marketing Management by Kotler",
    price: 550,
    category: "books",
    condition: "good",
    pickup: "library",
    imageUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&q=80",
    sellerName: "Divya Nair",
    sellerBatch: "MBA '24",
    location: "Library",
    postedAgo: "8 hours ago",
    createdAtOffsetMinutes: 480,
  },
  {
    id: "l11",
    title: "Electric Kettle 1.5L",
    price: 600,
    category: "hostel_essentials",
    condition: "like_new",
    pickup: "hostel",
    imageUrl: "https://images.unsplash.com/photo-1594213114663-d94db9b17125?w=600&q=80",
    sellerName: "Sameer Joshi",
    sellerBatch: "MBA '25",
    location: "Hostel 9",
    postedAgo: "1 day ago",
    createdAtOffsetMinutes: 1500,
  },
  {
    id: "l12",
    title: "Noise-Cancelling Headphones",
    price: 4200,
    category: "electronics",
    condition: "good",
    pickup: "academic_block",
    imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80",
    sellerName: "Neha Kapoor",
    sellerBatch: "FPM '25",
    location: "Academic Block",
    postedAgo: "10 hours ago",
    createdAtOffsetMinutes: 600,
  },
  {
    id: "l13",
    title: "Mini Fridge 45L",
    price: 5500,
    category: "appliances",
    condition: "fair",
    pickup: "hostel",
    imageUrl: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=600&q=80",
    sellerName: "Arjun Singh",
    sellerBatch: "MBA '24",
    location: "Hostel 11",
    postedAgo: "1 day ago",
    createdAtOffsetMinutes: 1600,
  },
  {
    id: "l14",
    title: "Financial Accounting Textbook",
    price: 400,
    category: "books",
    condition: "good",
    pickup: "hostel",
    imageUrl: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=600&q=80",
    sellerName: "Pooja Menon",
    sellerBatch: "MBA '25",
    location: "Hostel 4",
    postedAgo: "7 hours ago",
    createdAtOffsetMinutes: 420,
  },
  {
    id: "l15",
    title: "Bean Bag Chair (XL)",
    price: 900,
    category: "furniture",
    condition: "good",
    pickup: "other",
    imageUrl: "https://images.unsplash.com/photo-1519947486511-46149fa0a254?w=600&q=80",
    sellerName: "Ravi Teja",
    sellerBatch: "MBA '24",
    location: "Sports Complex",
    postedAgo: "9 hours ago",
    createdAtOffsetMinutes: 540,
  },
];
